[app]
name = "AI Bidding Assistant"
version = "0.1.0"
debug = true

[server]
host = "0.0.0.0"
backend_port = 8000
frontend_port = 7860
workers = 4

[database]
mysql_url = "mysql://user:password@localhost/ai_bidding"
redis_url = "redis://localhost:6379/0"
pool_size = 10
pool_recycle = 3600

[celery]
broker_url = "redis://localhost:6379/1"
result_backend = "redis://localhost:6379/2"
task_time_limit = 3600
task_soft_time_limit = 3000

[llm]
default_provider = "deepseek"
temperature = 0.7
max_tokens = 4000
request_timeout = 60

[llm.providers.deepseek]
api_key = "${DEEPSEEK_API_KEY}"
model = "deepseek-chat"
base_url = "https://api.deepseek.com/v1"

[llm.providers.openai]
api_key = "${OPENAI_API_KEY}"
model = "gpt-3.5-turbo"

[document]
max_file_size_mb = 50
allowed_extensions = ["pdf", "docx", "doc"]
chunk_size = 2000
chunk_overlap = 200

[workflow]
max_retries = 3
human_review_required = true

[logging]
level = "INFO"
format = "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
rotation = "1 day"
retention = "7 days"