# Prometheus配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AI投标系统后端监控
  - job_name: 'ai-bidding-backend'
    static_configs:
      - targets: ['ai-bidding:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  # 系统监控 (如果安装了node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
